version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: smartfridge-backend
    container_name: smartfridge-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: smartfridge-worker 
    container_name: smartfridge-worker
    restart: unless-stopped
    env_file:
      - .env
  